# Generated by Django 5.0.6 on 2026-04-08 21:35

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('side', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], max_length=4)),
                ('mode', models.CharField(choices=[('live', 'Live'), ('paper', 'Paper')], default='live', max_length=5)),
                ('quantity', models.DecimalField(decimal_places=8, max_digits=20)),
                ('price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=20)),
                ('fee', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=20)),
                ('realized_pnl', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TradeJournalEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('strategy', models.CharField(blank=True, default='', max_length=100)),
                ('emotion', models.CharField(blank=True, choices=[('confident', 'Confident'), ('fearful', 'Fearful'), ('greedy', 'Greedy'), ('neutral', 'Neutral'), ('fomo', 'FOMO')], default='', max_length=10)),
                ('outcome', models.CharField(blank=True, choices=[('win', 'Win'), ('loss', 'Loss'), ('be', 'Break-even')], default='', max_length=4)),
                ('rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('screenshot', models.ImageField(blank=True, null=True, upload_to='journal/screenshots/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('side', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], max_length=4)),
                ('order_type', models.CharField(choices=[('market', 'Market'), ('limit', 'Limit'), ('stop', 'Stop')], max_length=8)),
                ('status', models.CharField(choices=[('open', 'Open'), ('filled', 'Filled'), ('partial', 'Partially Filled'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected')], default='open', max_length=10)),
                ('mode', models.CharField(choices=[('live', 'Live'), ('paper', 'Paper')], default='live', max_length=5)),
                ('quantity', models.DecimalField(decimal_places=8, max_digits=20)),
                ('filled_qty', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=20)),
                ('limit_price', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('stop_price', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('avg_fill_price', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('exchange_order_id', models.CharField(blank=True, default='', max_length=128)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='market.asset')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
