# Generated by Django 5.0.6 on 2026-04-08 21:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('market', '0001_initial'),
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trade',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trades', to='market.asset'),
        ),
        migrations.AddField(
            model_name='trade',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fills', to='orders.order'),
        ),
        migrations.AddField(
            model_name='trade',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tradejournalentry',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_entries', to='orders.order'),
        ),
        migrations.AddField(
            model_name='tradejournalentry',
            name='trade',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal', to='orders.trade'),
        ),
        migrations.AddField(
            model_name='tradejournalentry',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user', 'status'], name='orders_orde_user_id_02a211_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['asset', 'status'], name='orders_orde_asset_i_fa01a3_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['mode', 'status'], name='orders_orde_mode_e70381_idx'),
        ),
        migrations.AddIndex(
            model_name='trade',
            index=models.Index(fields=['user', 'asset'], name='orders_trad_user_id_b398c7_idx'),
        ),
        migrations.AddIndex(
            model_name='trade',
            index=models.Index(fields=['mode', 'created_at'], name='orders_trad_mode_cf1c4b_idx'),
        ),
    ]
