# Generated by Django 5.0.6 on 2026-04-23 11:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0001_initial"),
        ("orders", "0002_initial"),
        ("strategies", "0004_strategy_instrument_type_strategy_risk_config_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="sl_price",
            field=models.DecimalField(
                blank=True, decimal_places=8, max_digits=20, null=True
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="strategy",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders",
                to="strategies.strategy",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="target_price",
            field=models.DecimalField(
                blank=True, decimal_places=8, max_digits=20, null=True
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["strategy", "status"], name="orders_orde_strateg_503631_idx"
            ),
        ),
    ]
