# Generated by Django 5.0.6 on 2026-04-24 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_order_sl_price_order_strategy_order_target_price_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="side",
            field=models.CharField(
                choices=[("buy", "Buy"), ("sell", "Sell")], max_length=5
            ),
        ),
    ]
