# Generated by Django 5.0.6 on 2026-05-03 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "brokers",
            "0005_remove_brokerorder_brokerorder_exactly_one_trade_fk_and_more",
        ),
        ("orders", "0004_alter_order_side"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="broker_account",
            field=models.ForeignKey(
                blank=True,
                help_text="Broker used to execute this order",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders",
                to="brokers.brokeraccount",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="broker_response",
            field=models.JSONField(
                blank=True, default=dict, help_text="Raw broker API response for audit"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="execution_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("sent", "Sent"),
                    ("accepted", "Accepted"),
                    ("rejected", "Rejected"),
                    ("failed", "Failed"),
                ],
                db_index=True,
                default="pending",
                max_length=12,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="rejection_reason",
            field=models.TextField(blank=True, default=""),
        ),
    ]
