# Generated by Django 5.0.6 on 2026-05-04 02:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0001_initial"),
        ("orders", "0005_order_broker_account_order_broker_response_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="trade",
            name="emoji_reaction",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Single emoji representing trade feeling: 😊, 😢, 🤔, 🔥, etc.",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="trade",
            name="funding_fee",
            field=models.DecimalField(
                blank=True,
                decimal_places=8,
                help_text="Funding fee charged/earned (Crypto perpetuals only)",
                max_digits=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="trade",
            name="leverage",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Leverage multiplier (Crypto futures only)",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="trade",
            name="lots",
            field=models.IntegerField(
                blank=True,
                help_text="Number of lots (Indian market: 1 lot = lot_size * quantity)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="trade",
            name="market_type",
            field=models.CharField(
                choices=[("indian", "Indian Market"), ("crypto", "Crypto Market")],
                db_index=True,
                default="indian",
                help_text="Indian (NSE/Options/Futures) or Crypto (Delta Exchange)",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="trade",
            name="notes",
            field=models.TextField(
                blank=True,
                default="",
                help_text="User's trade notes, strategy explanation, learnings",
            ),
        ),
        migrations.AddField(
            model_name="trade",
            name="option_type",
            field=models.CharField(
                blank=True,
                choices=[("CE", "Call"), ("PE", "Put")],
                default="",
                help_text="CE/PE for Indian options",
                max_length=2,
            ),
        ),
        migrations.AddField(
            model_name="trade",
            name="strike",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Strike price for options (Indian market only)",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="trade",
            name="tags",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of tag strings: ['breakout', 'daily-tf', 'missed-entry']",
            ),
        ),
        migrations.AddIndex(
            model_name="trade",
            index=models.Index(
                fields=["market_type", "created_at"],
                name="orders_trad_market__a8ee4d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="trade",
            index=models.Index(
                fields=["user", "market_type", "created_at"],
                name="orders_trad_user_id_491b52_idx",
            ),
        ),
    ]
