# Generated by Django 5.0.6 on 2026-05-12 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0006_trade_emoji_reaction_trade_funding_fee_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="client_order_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Flutter se aaya idempotency key — duplicate orders rokta hai",
                max_length=64,
                null=True,
                unique=True,
            ),
        ),
    ]
