# Generated by Django 5.0.6 on 2026-05-13 15:47

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("live_trading", "0002_alter_livesignal_status"),
        ("market", "0001_initial"),
        ("orders", "0007_order_client_order_id"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Position",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "side",
                    models.CharField(
                        choices=[("buy", "Buy"), ("sell", "Sell")],
                        help_text="BUY = Long position, SELL = Short position",
                        max_length=5,
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=8,
                        help_text="Total quantity when position opened",
                        max_digits=20,
                    ),
                ),
                (
                    "remaining_qty",
                    models.DecimalField(
                        decimal_places=8,
                        help_text="Remaining quantity (decreases with partial closes)",
                        max_digits=20,
                    ),
                ),
                (
                    "avg_entry_price",
                    models.DecimalField(
                        decimal_places=8, help_text="Average entry price", max_digits=20
                    ),
                ),
                (
                    "current_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=8,
                        help_text="Current market price (updated periodically)",
                        max_digits=20,
                        null=True,
                    ),
                ),
                (
                    "unrealized_pnl",
                    models.DecimalField(
                        decimal_places=8,
                        default=Decimal("0"),
                        help_text="Current unrealized P&L",
                        max_digits=20,
                    ),
                ),
                (
                    "realized_pnl",
                    models.DecimalField(
                        decimal_places=8,
                        default=Decimal("0"),
                        help_text="Realized P&L after closing",
                        max_digits=20,
                    ),
                ),
                (
                    "stop_loss",
                    models.DecimalField(
                        blank=True,
                        decimal_places=8,
                        help_text="Stop loss price",
                        max_digits=20,
                        null=True,
                    ),
                ),
                (
                    "take_profit",
                    models.DecimalField(
                        blank=True,
                        decimal_places=8,
                        help_text="Take profit target price",
                        max_digits=20,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("closed", "Closed"),
                            ("partial", "Partially Closed"),
                        ],
                        db_index=True,
                        default="open",
                        max_length=10,
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[("live", "Live"), ("paper", "Paper")],
                        default="live",
                        help_text="Live or Paper trading",
                        max_length=5,
                    ),
                ),
                ("opened_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="positions",
                        to="market.asset",
                    ),
                ),
                (
                    "live_signal",
                    models.ForeignKey(
                        blank=True,
                        help_text="LiveSignal jisse ye position trigger hua (if applicable)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="positions",
                        to="live_trading.livesignal",
                    ),
                ),
                (
                    "opening_order",
                    models.ForeignKey(
                        blank=True,
                        help_text="Order jisse ye position open hua",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="opened_positions",
                        to="orders.order",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="positions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Position",
                "verbose_name_plural": "Positions",
                "ordering": ["-opened_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "status"], name="orders_posi_user_id_10f3b4_idx"
                    ),
                    models.Index(
                        fields=["asset", "status"],
                        name="orders_posi_asset_i_aaa8d5_idx",
                    ),
                    models.Index(
                        fields=["status", "opened_at"],
                        name="orders_posi_status_78c9ee_idx",
                    ),
                    models.Index(
                        fields=["mode", "status"], name="orders_posi_mode_c0930e_idx"
                    ),
                ],
            },
        ),
    ]
