# Generated by Django 5.0.6 on 2026-06-07 02:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_position'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyPnlSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('mode', models.CharField(default='live', max_length=10)),
                ('market_type', models.CharField(default='all', max_length=10)),
                ('realised_pnl', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('unrealised_pnl', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('fees', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('total_trades', models.IntegerField(default=0)),
                ('wins', models.IntegerField(default=0)),
                ('losses', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_pnl_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('user', 'date', 'mode', 'market_type')},
            },
        ),
    ]
