# Generated by Django 5.0.6 on 2026-06-11 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_order_db_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='order',
            name='order_user_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='order_user_mode_idx',
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='order_symbol_status_idx',
        ),
    ]
