# Generated by Django 5.0.6 on 2026-06-11 11:16

from django.db import migrations


def copy_trade_journal_to_order(apps, schema_editor):
    """Copy Trade.notes/tags/emoji_reaction → parent Order before dropping Trade table."""
    Trade = apps.get_model("orders", "Trade")
    for trade in Trade.objects.select_related("order").iterator():
        order = trade.order
        changed = []
        if trade.notes and not order.journal_notes:
            order.journal_notes = trade.notes
            changed.append("journal_notes")
        if trade.tags and not order.tags:
            order.tags = trade.tags
            changed.append("tags")
        if trade.emoji_reaction and not order.emoji_reaction:
            order.emoji_reaction = trade.emoji_reaction
            changed.append("emoji_reaction")
        if trade.price and not order.avg_fill_price and not order.entry_price:
            order.avg_fill_price = trade.price
            changed.append("avg_fill_price")
        if trade.realized_pnl is not None and order.realized_pnl is None:
            order.realized_pnl = trade.realized_pnl
            changed.append("realized_pnl")
        if not order.instrument_type:
            if trade.market_type == "crypto":
                order.instrument_type = "crypto"
            elif trade.option_type in ("CE", "PE"):
                order.instrument_type = "options"
            else:
                order.instrument_type = "equity"
            changed.append("instrument_type")
        if changed:
            order.save(update_fields=changed)


def backfill_journal_entry_order(apps, schema_editor):
    """Set TradeJournalEntry.order = trade.order where order is null."""
    TradeJournalEntry = apps.get_model("orders", "TradeJournalEntry")
    for entry in TradeJournalEntry.objects.filter(trade__isnull=False, order__isnull=True).select_related("trade__order").iterator():
        if entry.trade and entry.trade.order_id:
            entry.order_id = entry.trade.order_id
            entry.save(update_fields=["order"])


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_remove_order_order_user_status_idx_and_more'),
    ]

    operations = [
        migrations.RunPython(
            copy_trade_journal_to_order,
            migrations.RunPython.noop,
        ),
        migrations.RunPython(
            backfill_journal_entry_order,
            migrations.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name='tradejournalentry',
            name='trade',
        ),
        migrations.DeleteModel(
            name='Trade',
        ),
    ]
