# Generated by Django 5.0.6 on 2026-05-02 12:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("brokers", "0003_brokeraccount_app_id_brokeraccount_is_verified_and_more"),
        ("options", "0004_optiontrade_confirmed_at_optiontrade_metadata"),
        ("paper_trading", "0008_alter_papertrade_exit_reason"),
    ]

    operations = [
        migrations.CreateModel(
            name="BrokerOrder",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "order_type",
                    models.CharField(
                        choices=[
                            ("entry", "Entry"),
                            ("sl", "Stop Loss"),
                            ("target", "Target"),
                            ("exit", "Exit"),
                        ],
                        default="entry",
                        max_length=10,
                    ),
                ),
                (
                    "exchange_order_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="ID returned by broker after placement (empty until sent)",
                        max_length=100,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("open", "Open"),
                            ("complete", "Complete"),
                            ("cancelled", "Cancelled"),
                            ("rejected", "Rejected"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("rejection_reason", models.TextField(blank=True, default="")),
                ("retry_count", models.PositiveSmallIntegerField(default=0)),
                ("max_retries", models.PositiveSmallIntegerField(default=3)),
                (
                    "next_retry_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Celery retry scheduled time (exponential backoff)",
                        null=True,
                    ),
                ),
                ("placed_at", models.DateTimeField(auto_now_add=True)),
                ("sent_to_broker_at", models.DateTimeField(blank=True, null=True)),
                ("executed_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "broker_response",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Raw broker API response — debug only, not exposed via API",
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "broker_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="broker_orders",
                        to="brokers.brokeraccount",
                    ),
                ),
                (
                    "option_trade",
                    models.ForeignKey(
                        blank=True,
                        help_text="NSE live options trade",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="broker_orders",
                        to="options.optiontrade",
                    ),
                ),
                (
                    "paper_trade",
                    models.ForeignKey(
                        blank=True,
                        help_text="Paper trade (crypto / futures / options simulation)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="broker_orders",
                        to="paper_trading.papertrade",
                    ),
                ),
            ],
            options={
                "ordering": ["-placed_at"],
                "indexes": [
                    models.Index(
                        fields=["broker_account", "status"],
                        name="brokers_bro_broker__b479aa_idx",
                    ),
                    models.Index(
                        fields=["option_trade", "order_type"],
                        name="brokers_bro_option__9e9fac_idx",
                    ),
                    models.Index(
                        fields=["paper_trade", "status"],
                        name="brokers_bro_paper_t_5660a2_idx",
                    ),
                    models.Index(
                        fields=["status", "next_retry_at"],
                        name="brokers_bro_status_e82a7c_idx",
                    ),
                    models.Index(
                        fields=["exchange_order_id"],
                        name="brokers_bro_exchang_df414e_idx",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="brokerorder",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("option_trade__isnull", False), ("paper_trade__isnull", True)
                    ),
                    models.Q(
                        ("option_trade__isnull", True), ("paper_trade__isnull", False)
                    ),
                    _connector="OR",
                ),
                name="brokerorder_exactly_one_trade_fk",
            ),
        ),
    ]
