# Generated by Django 5.0.6 on 2026-05-03 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("brokers", "0004_brokerorder_and_more"),
        ("options", "0004_optiontrade_confirmed_at_optiontrade_metadata"),
        ("orders", "0004_alter_order_side"),
        ("paper_trading", "0008_alter_papertrade_exit_reason"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="brokerorder",
            name="brokerorder_exactly_one_trade_fk",
        ),
        migrations.AddField(
            model_name="brokerorder",
            name="order",
            field=models.ForeignKey(
                blank=True,
                help_text="The Order this execution attempt belongs to (new flow)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="broker_executions",
                to="orders.order",
            ),
        ),
        migrations.AlterField(
            model_name="brokerorder",
            name="option_trade",
            field=models.ForeignKey(
                blank=True,
                help_text="NSE live options trade (legacy flow)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="broker_orders",
                to="options.optiontrade",
            ),
        ),
        migrations.AddConstraint(
            model_name="brokerorder",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("option_trade__isnull", True),
                        ("order__isnull", False),
                        ("paper_trade__isnull", True),
                    ),
                    models.Q(
                        ("option_trade__isnull", False),
                        ("order__isnull", True),
                        ("paper_trade__isnull", True),
                    ),
                    models.Q(
                        ("option_trade__isnull", True),
                        ("order__isnull", True),
                        ("paper_trade__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="brokerorder_exactly_one_trade_fk",
            ),
        ),
    ]
