# Generated by Django 5.0.6 on 2026-05-06 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "brokers",
            "0005_remove_brokerorder_brokerorder_exactly_one_trade_fk_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="brokeraccount",
            name="fyers_pin",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Fyers 4-digit PIN — daily auto-refresh ke liye (store encrypted in prod)",
                max_length=10,
            ),
        ),
    ]
