# Generated by Django 5.0.6 on 2026-05-12 12:02

import django.utils.timezone
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("brokers", "0006_brokeraccount_fyers_pin"),
        ("options", "0005_optiontrade_emoji_reaction_optiontrade_notes_and_more"),
        ("orders", "0007_order_client_order_id"),
        ("paper_trading", "0008_alter_papertrade_exit_reason"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="brokerorder",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="brokerorder",
            name="avg_fill_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Average execution price",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="brokerorder",
            name="broker_order_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="ID returned by broker API (unique per broker)",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="brokerorder",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, 
                default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="brokerorder",
            name="filled_at",
            field=models.DateTimeField(
                blank=True, help_text="Alias for executed_at (compatibility)", null=True
            ),
        ),
        migrations.AddField(
            model_name="brokerorder",
            name="filled_quantity",
            field=models.IntegerField(default=0, help_text="Quantity filled so far"),
        ),
        migrations.AddField(
            model_name="brokerorder",
            name="order_category",
            field=models.CharField(
                choices=[
                    ("market", "Market"),
                    ("limit", "Limit"),
                    ("stop_loss", "Stop Loss"),
                    ("sl_m", "Stop Loss Market"),
                    ("sl_l", "Stop Loss Limit"),
                ],
                default="market",
                help_text="Market, Limit, Stop Loss, etc.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="brokerorder",
            name="price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Limit price (for limit orders)",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="brokerorder",
            name="quantity",
            field=models.IntegerField(
                default=1,
                help_text="Total order quantity"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="brokerorder",
            name="side",
            field=models.CharField(
                choices=[("buy", "Buy"), ("sell", "Sell")],
                default="buy",
                help_text="Buy or Sell",
                max_length=10,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="brokerorder",
            name="symbol",
            field=models.CharField(
                default="UNKNOWN",
                help_text="Trading symbol (e.g., NIFTY24JUN21000CE, BTCUSDT)",
                max_length=100,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="brokerorder",
            name="trigger_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Stop loss trigger price",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="brokerorder",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="brokerorder",
            name="cancelled_at",
            field=models.DateTimeField(
                blank=True, help_text="When order was cancelled", null=True
            ),
        ),
        migrations.AlterField(
            model_name="brokerorder",
            name="exchange_order_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="Exchange order ID from broker (if different from broker_order_id)",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="brokerorder",
            name="executed_at",
            field=models.DateTimeField(
                blank=True, help_text="When order was fully filled", null=True
            ),
        ),
        migrations.AlterField(
            model_name="brokerorder",
            name="order_type",
            field=models.CharField(
                choices=[
                    ("entry", "Entry"),
                    ("sl", "Stop Loss"),
                    ("target", "Target"),
                    ("exit", "Exit"),
                ],
                default="entry",
                help_text="Entry, SL, Target, or Exit",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="brokerorder",
            name="placed_at",
            field=models.DateTimeField(
                blank=True, help_text="When order was first created in DB", null=True
            ),
        ),
        migrations.AlterField(
            model_name="brokerorder",
            name="sent_to_broker_at",
            field=models.DateTimeField(
                blank=True, help_text="When order was sent to broker API", null=True
            ),
        ),
        migrations.AlterField(
            model_name="brokerorder",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("placed", "Placed"),
                    ("open", "Open"),
                    ("partial", "Partially Filled"),
                    ("complete", "Complete"),
                    ("filled", "Filled"),
                    ("cancelled", "Cancelled"),
                    ("rejected", "Rejected"),
                    ("failed", "Failed"),
                ],
                db_index=True,
                default="pending",
                max_length=20,
            ),
        ),
        
        # ── REMOVED: AddField for 'order' (already exists in DB) ──
        # The order_id column already exists from a previous migration
        # We'll only update the CheckConstraint to include it
        
        migrations.AddIndex(
            model_name="brokerorder",
            index=models.Index(
                fields=["order", "status"], name="brokers_bro_order_i_3db86a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="brokerorder",
            index=models.Index(
                fields=["broker_order_id"], name="brokers_bro_broker__e89d68_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="brokerorder",
            index=models.Index(
                fields=["symbol", "status"], name="brokers_bro_symbol_140a43_idx"
            ),
        ),
        
        # Update CheckConstraint to include the existing 'order' FK
        migrations.RemoveConstraint(
            model_name="brokerorder",
            name="brokerorder_exactly_one_trade_fk",
        ),
        migrations.AddConstraint(
            model_name="brokerorder",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("order__isnull", False),
                    ("option_trade__isnull", True),
                    ("paper_trade__isnull", True),
                ) | models.Q(
                    ("order__isnull", True),
                    ("option_trade__isnull", False),
                    ("paper_trade__isnull", True),
                ) | models.Q(
                    ("order__isnull", True),
                    ("option_trade__isnull", True),
                    ("paper_trade__isnull", False),
                ),
                name="brokerorder_exactly_one_trade_fk",
            ),
        ),
    ]