# Generated by Django 5.0.6 on 2026-05-13 06:11

import apps.brokers.encryption
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "brokers",
            "0007_alter_brokerorder_options_brokerorder_avg_fill_price_and_more",
        ),
        ("options", "0005_optiontrade_emoji_reaction_optiontrade_notes_and_more"),
        ("orders", "0007_order_client_order_id"),
        ("paper_trading", "0008_alter_papertrade_exit_reason"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="brokerorder",
            name="brokerorder_exactly_one_trade_fk",
        ),
        migrations.AlterField(
            model_name="brokeraccount",
            name="fyers_pin",
            field=apps.brokers.encryption.EncryptedCharField(
                blank=True,
                default="",
                help_text="Fyers 4-digit PIN — Fernet-encrypted at rest. Plain text kabhi store nahi hota.",
                max_length=10,
            ),
        ),
        migrations.AddConstraint(
            model_name="brokerorder",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("option_trade__isnull", True),
                        ("order__isnull", False),
                        ("paper_trade__isnull", True),
                    ),
                    models.Q(
                        ("option_trade__isnull", False),
                        ("order__isnull", True),
                        ("paper_trade__isnull", True),
                    ),
                    models.Q(
                        ("option_trade__isnull", True),
                        ("order__isnull", True),
                        ("paper_trade__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="brokerorder_exactly_one_trade_fk",
            ),
        ),
    ]
