# Generated by Django 5.0.6 on 2026-05-13 07:46

import apps.brokers.encryption
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "brokers",
            "0008_remove_brokerorder_brokerorder_exactly_one_trade_fk_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="brokeraccount",
            name="totp_secret",
            field=apps.brokers.encryption.EncryptedCharField(
                blank=True,
                default="",
                help_text="Fyers TOTP secret key — Fernet-encrypted at rest. Plain text kabhi store nahi hota.",
                max_length=32,
            ),
        ),
    ]
