# Generated by Django 5.0.6 on 2026-05-16 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("brokers", "0009_brokeraccount_totp_secret"),
    ]

    operations = [
        migrations.AddField(
            model_name="brokerorder",
            name="realized_pnl",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Net realized PnL in INR after this order filled (fees deducted). Null for BUY/entry orders; populated on SELL/exit fill.",
                max_digits=14,
                null=True,
            ),
        ),
    ]
