# Generated by Django 5.0.6 on 2026-05-31 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brokers', '0014_zerodha_broker_support'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brokeraccount',
            name='zerodha_request_token',
            field=models.CharField(blank=True, default='', help_text='Temporary request_token (cleared after exchange)', max_length=500),
        ),
    ]
