# Generated by Django 5.0.6 on 2026-06-11 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brokers', '0015_alter_brokeraccount_zerodha_request_token'),
        ('orders', '0013_remove_order_order_user_status_idx_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='brokerorder',
            name='brokerorder_exactly_one_trade_fk',
        ),
        migrations.RemoveIndex(
            model_name='brokerorder',
            name='brokers_bro_option__9e9fac_idx',
        ),
        migrations.RemoveIndex(
            model_name='brokerorder',
            name='brokers_bro_paper_t_5660a2_idx',
        ),
        migrations.RemoveField(
            model_name='brokerorder',
            name='option_trade',
        ),
        migrations.RemoveField(
            model_name='brokerorder',
            name='paper_trade',
        ),
        migrations.AlterField(
            model_name='brokerorder',
            name='order',
            field=models.ForeignKey(blank=True, help_text='The Order this execution attempt belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='broker_executions', to='orders.order'),
        ),
    ]
