# Generated by Django 5.0.6 on 2026-04-09 11:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OptionContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strike', models.FloatField()),
                ('option_type', models.CharField(choices=[('CE', 'Call'), ('PE', 'Put')], max_length=2)),
                ('expiry', models.DateField()),
                ('fyers_symbol', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='OptionSymbol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('fyers_symbol', models.CharField(max_length=50)),
                ('lot_size', models.IntegerField(default=75)),
                ('strike_step', models.IntegerField(default=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='OptionPaperAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.FloatField(default=500000.0)),
                ('total_pnl', models.FloatField(default=0.0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='option_paper_account', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OptionSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ltp', models.FloatField()),
                ('oi', models.BigIntegerField(default=0)),
                ('volume', models.BigIntegerField(default=0)),
                ('iv', models.FloatField(blank=True, null=True)),
                ('delta', models.FloatField(blank=True, null=True)),
                ('theta', models.FloatField(blank=True, null=True)),
                ('spot_price', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='options.optioncontract')),
            ],
            options={
                'get_latest_by': 'timestamp',
            },
        ),
        migrations.AddField(
            model_name='optioncontract',
            name='symbol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='options.optionsymbol'),
        ),
        migrations.CreateModel(
            name='BacktestRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('strategy', models.CharField(default='ICT_MTF', max_length=50)),
                ('initial_capital', models.FloatField(default=500000)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('final_capital', models.FloatField(blank=True, null=True)),
                ('total_pnl', models.FloatField(blank=True, null=True)),
                ('win_rate', models.FloatField(blank=True, null=True)),
                ('max_drawdown', models.FloatField(blank=True, null=True)),
                ('total_trades', models.IntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='options.optionsymbol')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='optioncontract',
            unique_together={('symbol', 'strike', 'option_type', 'expiry')},
        ),
        migrations.CreateModel(
            name='OptionTrade',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('mode', models.CharField(choices=[('paper', 'Paper'), ('live', 'Live')], max_length=10)),
                ('action', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], max_length=4)),
                ('lots', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('entry_price', models.FloatField()),
                ('target_price', models.FloatField()),
                ('stop_loss', models.FloatField()),
                ('current_price', models.FloatField(blank=True, null=True)),
                ('entry_spot', models.FloatField()),
                ('current_spot', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=10)),
                ('exit_price', models.FloatField(blank=True, null=True)),
                ('exit_reason', models.CharField(blank=True, max_length=20)),
                ('pnl', models.FloatField(blank=True, null=True)),
                ('setup_type', models.CharField(default='Manual', max_length=50)),
                ('timeframe', models.CharField(default='15', max_length=10)),
                ('entry_time', models.DateTimeField(auto_now_add=True)),
                ('exit_time', models.DateTimeField(blank=True, null=True)),
                ('backtest_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='options.backtestrun')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='options.optioncontract')),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='options.optionsymbol')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='option_trades', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-entry_time'],
                'indexes': [models.Index(fields=['user', 'status', 'mode'], name='options_opt_user_id_a2330c_idx'), models.Index(fields=['entry_time'], name='options_opt_entry_t_ac8339_idx')],
            },
        ),
    ]
