# Generated by Django 5.0.6 on 2026-04-23 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("options", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="OptionPaperAccount",
        ),
    ]
