# Generated by Django 5.0.6 on 2026-04-30 13:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("options", "0002_delete_optionpaperaccount"),
        ("strategies", "0004_strategy_instrument_type_strategy_risk_config_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="optiontrade",
            name="strategy",
            field=models.ForeignKey(
                blank=True,
                help_text="Strategy that created this trade (optional for manual trades)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="option_trades",
                to="strategies.strategy",
            ),
        ),
        migrations.AddIndex(
            model_name="optiontrade",
            index=models.Index(
                fields=["strategy", "status"], name="options_opt_strateg_8c8c3c_idx"
            ),
        ),
    ]
