# Generated by Django 5.0.6 on 2026-05-02 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("options", "0003_optiontrade_strategy_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="optiontrade",
            name="confirmed_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When user confirmed this trade (for manual execution)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="optiontrade",
            name="metadata",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Stores: signal_strength, indicators, executed_by, confirmation_time, notes",
            ),
        ),
    ]
