# Generated by Django 5.0.6 on 2026-05-04 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("options", "0004_optiontrade_confirmed_at_optiontrade_metadata"),
    ]

    operations = [
        migrations.AddField(
            model_name="optiontrade",
            name="emoji_reaction",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Emoji representing trade outcome/feeling: 😊, 😢, 🔥, 🤔",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="optiontrade",
            name="notes",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Trade notes: setup explanation, learnings, mistakes",
            ),
        ),
        migrations.AddField(
            model_name="optiontrade",
            name="tags",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Tags for filtering: ['fvg', 'order-block', 'breakout', 'revenge-trade']",
            ),
        ),
        migrations.AlterField(
            model_name="optiontrade",
            name="metadata",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Stores: signal_strength, indicators, executed_by, confirmation_time",
            ),
        ),
    ]
