# Generated by Django 5.0.6 on 2026-06-07 04:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('options', '0005_optiontrade_emoji_reaction_optiontrade_notes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OptionChainSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expiry', models.DateField()),
                ('spot', models.FloatField()),
                ('pcr_oi', models.FloatField(blank=True, null=True)),
                ('pcr_volume', models.FloatField(blank=True, null=True)),
                ('max_pain', models.FloatField(blank=True, null=True)),
                ('atm_strike', models.IntegerField(blank=True, null=True)),
                ('atm_ce_iv', models.FloatField(blank=True, null=True)),
                ('atm_pe_iv', models.FloatField(blank=True, null=True)),
                ('vix', models.FloatField(blank=True, null=True)),
                ('call_wall', models.FloatField(blank=True, null=True)),
                ('put_wall', models.FloatField(blank=True, null=True)),
                ('chain_data', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chain_snapshots', to='options.optionsymbol')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OptionsPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expiry', models.DateField()),
                ('direction', models.CharField(choices=[('bullish', 'Bullish'), ('bearish', 'Bearish'), ('neutral', 'Neutral')], max_length=10)),
                ('confidence_pct', models.FloatField(default=0)),
                ('signal_score', models.FloatField(default=0)),
                ('expected_range_low', models.FloatField(blank=True, null=True)),
                ('expected_range_high', models.FloatField(blank=True, null=True)),
                ('max_pain', models.FloatField(blank=True, null=True)),
                ('call_wall', models.FloatField(blank=True, null=True)),
                ('put_wall', models.FloatField(blank=True, null=True)),
                ('breakeven_pts', models.FloatField(blank=True, null=True)),
                ('up_prob', models.FloatField(default=0)),
                ('flat_prob', models.FloatField(default=0)),
                ('down_prob', models.FloatField(default=0)),
                ('suggested_strategy', models.CharField(blank=True, max_length=50, null=True)),
                ('strategy_legs', models.JSONField(default=list)),
                ('pcr_oi', models.FloatField(blank=True, null=True)),
                ('iv_rank', models.FloatField(blank=True, null=True)),
                ('signal_factors', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('snapshot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='options.optionchainsnapshot')),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='options.optionsymbol')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IVHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('atm_iv', models.FloatField()),
                ('iv_rank', models.FloatField(blank=True, null=True)),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iv_history', to='options.optionsymbol')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('symbol', 'date')},
            },
        ),
    ]
