# Generated by Django 5.0.6 on 2026-06-11 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brokers', '0016_remove_brokerorder_brokerorder_exactly_one_trade_fk_and_more'),
        ('options', '0006_optionchainsnapshot_optionsprediction_ivhistory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OptionTrade',
        ),
    ]
