# Generated by Django 5.0.6 on 2026-04-08 21:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('algo_name', models.CharField(max_length=100)),
                ('symbol', models.CharField(max_length=30)),
                ('mode', models.CharField(choices=[('paper', 'Paper'), ('live', 'Live')], default='paper', max_length=10)),
                ('state', models.CharField(choices=[('idle', 'Idle'), ('running', 'Running'), ('error', 'Error')], default='idle', max_length=10)),
                ('interval_seconds', models.PositiveIntegerField(default=60)),
                ('parameters', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('error_msg', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('stopped_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'strategies',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StrategyPerformanceSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('granularity', models.CharField(choices=[('hourly', 'Hourly'), ('daily', 'Daily')], max_length=10)),
                ('period_start', models.DateTimeField()),
                ('total_trades', models.IntegerField(default=0)),
                ('win_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('total_pnl', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('total_fees', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'strategy_performance_snapshots',
                'ordering': ['-period_start'],
            },
        ),
        migrations.CreateModel(
            name='StrategySignal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('signal_type', models.CharField(max_length=20)),
                ('symbol', models.CharField(max_length=30)),
                ('price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('reason', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('result', models.CharField(default='skipped', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'strategy_signals',
                'ordering': ['-created_at'],
            },
        ),
    ]
