# Generated by Django 5.0.6 on 2026-04-16 13:26

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategies', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategy',
            name='symbols',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), blank=True, default=list, help_text="['NIFTY', 'BANKNIFTY', 'FINNIFTY']", size=None),
        ),
    ]
