# Generated by Django 5.0.6 on 2026-04-19 06:23

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategies', '0003_strategy_symbols'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategy',
            name='instrument_type',
            field=models.CharField(choices=[('options', 'Options'), ('futures', 'Futures'), ('equity', 'Equity'), ('perp', 'Perpetual')], default='futures', help_text='Fyers: options/futures/equity | Delta: futures/perp', max_length=10),
        ),
        migrations.AddField(
            model_name='strategy',
            name='risk_config',
            field=models.JSONField(blank=True, default=dict, help_text='Per-strategy risk params: sl_pct, target_pct, qty, rr_ratio etc.'),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='symbols',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), blank=True, default=list, help_text="['NIFTY', 'BANKNIFTY'] ya ['BTCUSDT', 'ETHUSDT']", size=None),
        ),
    ]
