# Generated by Django 5.0.6 on 2026-05-04 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "brokers",
            "0005_remove_brokerorder_brokerorder_exactly_one_trade_fk_and_more",
        ),
        ("strategies", "0004_strategy_instrument_type_strategy_risk_config_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="strategy",
            name="broker",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="strategies",
                to="brokers.brokeraccount",
            ),
        ),
    ]
