# Generated by Django 5.0.6 on 2026-05-11 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("strategies", "0005_fix_broker_fk"),
    ]

    operations = [
        migrations.AddField(
            model_name="strategy",
            name="default_lots",
            field=models.PositiveIntegerField(
                default=1,
                help_text="Default lots per trade. risk_config['qty'] se override hota hai.",
            ),
        ),
        migrations.AddField(
            model_name="strategy",
            name="timeframe",
            field=models.CharField(
                choices=[
                    ("1", "1 Minute"),
                    ("5", "5 Minutes"),
                    ("15", "15 Minutes"),
                    ("30", "30 Minutes"),
                    ("60", "1 Hour"),
                    ("240", "4 Hours"),
                    ("1440", "1 Day"),
                ],
                default="15",
                help_text="Signal detection timeframe (minutes). risk_config['timeframe'] se override hota hai.",
                max_length=5,
            ),
        ),
    ]
