# Generated by Django 5.0.6 on 2026-05-21 05:14

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("strategies", "0006_strategy_default_lots_strategy_timeframe"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="strategy",
            name="allowed_plans",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=20),
                blank=True,
                default=list,
                help_text="Kon se plans ke users ko yeh global strategy dikhe. Empty = sab plans ke users. e.g. ['basic', 'pro', 'elite']",
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="strategy",
            name="created_by_admin",
            field=models.BooleanField(
                default=False,
                help_text="Admin panel se create ki gayi strategy hai ya user ne.",
            ),
        ),
        migrations.AddField(
            model_name="strategy",
            name="is_global",
            field=models.BooleanField(
                default=False,
                help_text="True = Admin ne banaya hai, sab eligible users ko dikhe. False = Sirf us user ko dikhe jiska strategy hai.",
            ),
        ),
        migrations.AlterField(
            model_name="strategy",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="strategies",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
