# Generated by Django 5.0.6 on 2026-05-28 19:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "strategies",
            "0007_strategy_allowed_plans_strategy_created_by_admin_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserStrategyPreference",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "preferred_mode",
                    models.CharField(
                        choices=[("paper", "Paper Trading"), ("live", "Live Trading")],
                        default="paper",
                        help_text="User ka chosen mode: paper ya live",
                        max_length=10,
                    ),
                ),
                (
                    "is_running",
                    models.BooleanField(
                        default=False,
                        help_text="Is user ke liye yeh strategy chal rahi hai?",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "strategy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_preferences",
                        to="strategies.strategy",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="strategy_preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Strategy Preference",
                "verbose_name_plural": "User Strategy Preferences",
                "unique_together": {("user", "strategy")},
            },
        ),
    ]
