# Generated by Django 5.0.6 on 2026-06-03 20:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategies', '0008_userstrategypreference'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserScreenerPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('execution_mode', models.CharField(choices=[('auto', 'Auto (Immediate Execution)'), ('semi', 'Semi (Alert + 60s Confirm)'), ('manual', 'Manual (Show Only)')], default='semi', help_text='Signal aane pe kya karna hai', max_length=10)),
                ('trading_mode', models.CharField(choices=[('paper', 'Paper Trading'), ('live', 'Live Trading')], default='paper', help_text='Paper ya live trade execute karo', max_length=10)),
                ('options_enabled', models.BooleanField(default=True)),
                ('crypto_enabled', models.BooleanField(default=True)),
                ('risk_pct', models.FloatField(default=1.0, help_text='Risk % per trade')),
                ('leverage', models.IntegerField(default=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='screener_preference', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Screener Preference',
                'verbose_name_plural': 'User Screener Preferences',
            },
        ),
    ]
