# Generated by Django 5.0.6 on 2026-06-10 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategies', '0009_userscreenerpreference'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstrategypreference',
            name='exit_mode',
            field=models.CharField(choices=[('gtt_oco', 'GTT OCO — Fixed SL/Target'), ('smart_trail', 'Smart Trail — Trailing SL'), ('both', 'Both — Trail + GTT backup')], default='gtt_oco', help_text='Per-strategy exit order type for live options trades', max_length=20),
        ),
    ]
