# Generated by Django 5.0.6 on 2026-04-08 21:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('symbol', models.CharField(db_index=True, max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('asset_type', models.CharField(choices=[('equity', 'Equity'), ('crypto', 'Crypto'), ('futures', 'Futures'), ('options', 'Options'), ('index', 'Index')], default='equity', max_length=10)),
                ('exchange', models.CharField(blank=True, max_length=20)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('last_price', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('lot_size', models.PositiveIntegerField(default=1)),
                ('tick_size', models.DecimalField(decimal_places=5, default='0.05', max_digits=10)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'market_assets',
                'ordering': ['symbol'],
            },
        ),
        migrations.CreateModel(
            name='MarketQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ltp', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('bid', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('ask', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('volume', models.BigIntegerField(default=0)),
                ('change', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('change_pct', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('high', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('low', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('open', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('prev_close', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quote', to='market.asset')),
            ],
            options={
                'db_table': 'market_quotes',
            },
        ),
    ]
