# Generated by Django 5.0.6 on 2026-04-08 21:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('razorpay_order_id', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('razorpay_payment_id', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('razorpay_signature', models.CharField(blank=True, default='', max_length=256)),
                ('amount_inr', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('payment_status', models.CharField(choices=[('created', 'Created'), ('captured', 'Captured'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='created', max_length=10)),
                ('raw_payload', models.JSONField(default=dict)),
                ('failure_reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('tier', models.IntegerField(choices=[(0, 'Free'), (1, 'Basic'), (2, 'Pro'), (3, 'Elite')])),
                ('billing_cycle', models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], default='monthly', max_length=10)),
                ('razorpay_plan_id', models.CharField(blank=True, default='', max_length=100)),
                ('price_inr', models.DecimalField(decimal_places=2, max_digits=10)),
                ('feature_limits', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['tier', 'billing_cycle'],
            },
        ),
        migrations.CreateModel(
            name='RazorpayWebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('event_type', models.CharField(max_length=100)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('payload', models.JSONField(default=dict)),
            ],
            options={
                'ordering': ['-processed_at'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('trialing', 'Trialing'), ('active', 'Active'), ('past_due', 'Past Due'), ('cancelled', 'Cancelled'), ('expired', 'Expired'), ('paused', 'Paused')], db_index=True, default='trialing', max_length=12)),
                ('razorpay_subscription_id', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('razorpay_customer_id', models.CharField(blank=True, default='', max_length=100)),
                ('current_period_start', models.DateTimeField(blank=True, null=True)),
                ('current_period_end', models.DateTimeField(blank=True, null=True)),
                ('grace_until', models.DateTimeField(blank=True, null=True)),
                ('trial_end', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
