# Generated by Django 5.0.6 on 2026-05-04 07:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TradingSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "strategy_id",
                    models.CharField(
                        help_text="UserStrategy.id (algo_name)", max_length=64
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("auto", "Auto (Immediate Execution)"),
                            ("semi_auto", "Semi-Auto (Alert + 60s Confirmation)"),
                            ("manual", "Manual (FAB Order Placement)"),
                        ],
                        default="semi_auto",
                        max_length=16,
                    ),
                ),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("total_trades", models.IntegerField(default=0)),
                ("winning_trades", models.IntegerField(default=0)),
                (
                    "total_pnl",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "max_drawdown",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "peak_equity",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trading_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="ManualOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symbol", models.CharField(max_length=32)),
                ("direction", models.CharField(max_length=8)),
                ("order_type", models.CharField(default="MARKET", max_length=16)),
                ("lots", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "price",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=16, null=True
                    ),
                ),
                (
                    "stop_loss",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=16, null=True
                    ),
                ),
                (
                    "take_profit",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=16, null=True
                    ),
                ),
                (
                    "rr_ratio",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                (
                    "margin_req",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("placed", "Placed"),
                            ("filled", "Filled"),
                            ("rejected", "Rejected"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        max_length=16,
                    ),
                ),
                ("broker_order_id", models.CharField(blank=True, max_length=64)),
                ("placed_at", models.DateTimeField(blank=True, null=True)),
                ("filled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "fill_price",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=16, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="manual_orders",
                        to="live_trading.tradingsession",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LiveSignal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("strategy_id", models.CharField(max_length=64)),
                ("symbol", models.CharField(max_length=32)),
                ("direction", models.CharField(max_length=8)),
                ("signal_type", models.CharField(max_length=32)),
                ("strength", models.CharField(max_length=16)),
                ("entry_price", models.DecimalField(decimal_places=6, max_digits=16)),
                ("stop_loss", models.DecimalField(decimal_places=6, max_digits=16)),
                ("take_profit", models.DecimalField(decimal_places=6, max_digits=16)),
                (
                    "rr_ratio",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                (
                    "lots",
                    models.DecimalField(decimal_places=2, default=1, max_digits=8),
                ),
                (
                    "margin_req",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("auto", "Auto (Immediate Execution)"),
                            ("semi_auto", "Semi-Auto (Alert + 60s Confirmation)"),
                            ("manual", "Manual (FAB Order Placement)"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("confirmed", "Confirmed"),
                            ("expired", "Expired"),
                            ("executed", "Executed"),
                            ("ignored", "Ignored"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                (
                    "detected_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("acted_at", models.DateTimeField(blank=True, null=True)),
                ("raw_payload", models.JSONField(default=dict)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="live_signals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="signals",
                        to="live_trading.tradingsession",
                    ),
                ),
            ],
            options={
                "ordering": ["-detected_at"],
            },
        ),
        migrations.CreateModel(
            name="ActivityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("executed", "Executed"),
                            ("ignored", "Ignored"),
                            ("expired", "Expired"),
                            ("pending", "Pending Confirmation"),
                            ("failed", "Failed"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("auto", "Auto (Immediate Execution)"),
                            ("semi_auto", "Semi-Auto (Alert + 60s Confirmation)"),
                            ("manual", "Manual (FAB Order Placement)"),
                        ],
                        max_length=16,
                    ),
                ),
                ("symbol", models.CharField(max_length=32)),
                ("direction", models.CharField(max_length=8)),
                (
                    "entry_price",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=16, null=True
                    ),
                ),
                (
                    "pnl",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=256)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("metadata", models.JSONField(default=dict)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "signal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="logs",
                        to="live_trading.livesignal",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activity_logs",
                        to="live_trading.tradingsession",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="tradingsession",
            index=models.Index(
                fields=["user", "is_active"], name="live_tradin_user_id_a683a7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="livesignal",
            index=models.Index(
                fields=["user", "status"], name="live_tradin_user_id_339901_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="livesignal",
            index=models.Index(
                fields=["session", "detected_at"], name="live_tradin_session_367d71_idx"
            ),
        ),
    ]
