# Generated by Django 5.0.6 on 2026-05-11 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("live_trading", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="livesignal",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("processing", "Processing"),
                    ("confirmed", "Confirmed"),
                    ("expired", "Expired"),
                    ("executed", "Executed"),
                    ("ignored", "Ignored"),
                ],
                default="pending",
                max_length=16,
            ),
        ),
    ]
