# Generated by Django 5.0.6 on 2026-04-22 13:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaperAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('balance', models.DecimalField(decimal_places=2, default=100000, max_digits=14)),
                ('initial_capital', models.DecimalField(decimal_places=2, default=100000, max_digits=14)),
                ('free_limit', models.DecimalField(decimal_places=2, default=100000, max_digits=14)),
                ('is_free_plan', models.BooleanField(default=True)),
                ('total_topup', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_withdrawn', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('daily_loss_limit', models.DecimalField(decimal_places=2, default=-5000, max_digits=14)),
                ('max_open_trades', models.IntegerField(default=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='paper_account', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PaperTopUp',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('payment_id', models.CharField(blank=True, max_length=100)),
                ('provider', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topups', to='paper_trading.paperaccount')),
            ],
        ),
        migrations.CreateModel(
            name='PaperTrade',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('symbol', models.CharField(max_length=50)),
                ('asset_type', models.CharField(choices=[('option', 'Option'), ('futures', 'Futures'), ('crypto', 'Crypto')], max_length=10)),
                ('display_name', models.CharField(blank=True, max_length=100)),
                ('side', models.CharField(choices=[('buy', 'Buy / Long'), ('sell', 'Sell / Short')], max_length=4)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=10)),
                ('lot_size', models.IntegerField(default=1)),
                ('leverage', models.IntegerField(default=1)),
                ('entry_price', models.DecimalField(decimal_places=4, max_digits=14)),
                ('current_price', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('stop_loss', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('target_price', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('exit_price', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('strike_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('option_type', models.CharField(blank=True, max_length=4)),
                ('pnl', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('margin_used', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=10)),
                ('exit_reason', models.CharField(blank=True, choices=[('target', 'Target Hit'), ('sl', 'Stop Loss Hit'), ('manual', 'Manual Close')], max_length=10)),
                ('setup_type', models.CharField(blank=True, max_length=50)),
                ('strategy_id', models.CharField(blank=True, max_length=100)),
                ('nifty_spot_at_entry', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='paper_trading.paperaccount')),
            ],
            options={
                'ordering': ['-opened_at'],
            },
        ),
    ]
