# Generated by Django 5.0.6 on 2026-04-24 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("paper_trading", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="papertrade",
            name="asset_type",
            field=models.CharField(
                choices=[
                    ("option", "Option"),
                    ("futures", "Futures"),
                    ("crypto", "Crypto"),
                ],
                max_length=20,
            ),
        ),
    ]
