# Generated by Django 5.0.6 on 2026-04-25 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("paper_trading", "0003_add_indexes"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="papertrade",
            name="idx_status_account",
        ),
        migrations.RemoveIndex(
            model_name="papertrade",
            name="idx_strategy_status",
        ),
        migrations.RenameIndex(
            model_name="papertrade",
            new_name="paper_tradi_symbol_64f4a7_idx",
            old_name="idx_symbol_status",
        ),
        migrations.AddIndex(
            model_name="papertrade",
            index=models.Index(
                fields=["account", "status"], name="paper_tradi_account_d1baf3_idx"
            ),
        ),
    ]
