# Generated by Django 5.0.6 on 2026-04-25 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("paper_trading", "0004_remove_papertrade_idx_status_account_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="papertrade",
            name="option_type",
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
