# Generated by Django 5.0.6 on 2026-04-25 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("paper_trading", "0005_alter_papertrade_option_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="papertrade",
            name="side",
            field=models.CharField(
                choices=[
                    ("buy", "Buy"),
                    ("sell", "Sell"),
                    ("long", "Long"),
                    ("short", "Short"),
                ],
                max_length=10,
            ),
        ),
    ]
