# Generated by Django 5.0.6 on 2026-04-27 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("paper_trading", "0006_increase_side_field_length"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="paperaccount",
            name="daily_loss_limit",
        ),
        migrations.RemoveField(
            model_name="paperaccount",
            name="max_open_trades",
        ),
        migrations.AddField(
            model_name="paperaccount",
            name="daily_loss_limit_fixed",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Fixed daily loss limit (overrides tier % if use_percentage_limit=False)",
                max_digits=14,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="paperaccount",
            name="use_percentage_limit",
            field=models.BooleanField(
                default=True,
                help_text="Use percentage-based limit (True) or fixed amount (False)",
            ),
        ),
    ]
