# Generated by Django 5.0.6 on 2026-04-29 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("paper_trading", "0007_remove_paperaccount_daily_loss_limit_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="papertrade",
            name="exit_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("target", "Target Hit"),
                    ("sl", "Stop Loss Hit"),
                    ("manual", "Manual Close"),
                ],
                max_length=50,
            ),
        ),
    ]
