# Generated by Django 5.0.6 on 2026-06-11 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brokers', '0016_remove_brokerorder_brokerorder_exactly_one_trade_fk_and_more'),
        ('paper_trading', '0008_alter_papertrade_exit_reason'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PaperTrade',
        ),
    ]
