# Generated by Django 5.0.6 on 2026-04-08 21:35

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('currency', models.CharField(default='USDT', help_text='Currency symbol, e.g. USDT, BTC', max_length=20)),
                ('available_balance', models.DecimalField(decimal_places=8, default=0, help_text='Trade ya withdraw ke liye available.', max_digits=28)),
                ('locked_balance', models.DecimalField(decimal_places=8, default=0, help_text='Open orders ke liye lock hua balance.', max_digits=28)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Wallet',
                'verbose_name_plural': 'Wallets',
                'ordering': ['user', 'currency'],
                'unique_together': {('user', 'currency')},
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('trade_settlement', 'Trade Settlement'), ('fee', 'Fee'), ('lock', 'Funds Locked'), ('unlock', 'Funds Unlocked'), ('adjustment', 'Manual Adjustment')], default='trade_settlement', max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='completed', max_length=20)),
                ('amount', models.DecimalField(decimal_places=8, help_text='Transaction ki gross amount.', max_digits=28)),
                ('fee', models.DecimalField(decimal_places=8, default=0, help_text='Is transaction par lagi fee.', max_digits=28)),
                ('reference', models.CharField(blank=True, default='', help_text='External ya internal reference (trade_id, txn_hash, etc.)', max_length=255)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='wallet.wallet')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
