# Generated by Django 5.0.6 on 2026-04-08 21:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BacktestRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('symbol', models.CharField(max_length=20)),
                ('timeframe', models.CharField(default='1h', max_length=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('strategy_name', models.CharField(max_length=100)),
                ('strategy_params', models.JSONField(default=dict)),
                ('initial_capital', models.DecimalField(decimal_places=2, default=10000, max_digits=20)),
                ('fee_rate', models.DecimalField(decimal_places=6, default=0.001, max_digits=8)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('error_message', models.TextField(blank=True, default='')),
                ('results', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
