# Generated by Django 5.0.6 on 2026-04-13 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtest', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='backtestrun',
            name='celery_task_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
