# Generated by Django 5.0.6 on 2026-06-07 14:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtest', '0003_backtestrun_celery_task_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OptimizerRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('strategy_name', models.CharField(max_length=100)),
                ('symbol', models.CharField(max_length=20)),
                ('timeframe', models.CharField(default='15', max_length=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('initial_capital', models.DecimalField(decimal_places=2, default=100000, max_digits=20)),
                ('param_ranges', models.JSONField(default=dict)),
                ('objective', models.CharField(default='balanced', max_length=50)),
                ('train_ratio', models.FloatField(default=0.7)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('error_message', models.TextField(blank=True, default='')),
                ('celery_task_id', models.CharField(blank=True, max_length=255, null=True)),
                ('progress', models.IntegerField(default=0)),
                ('total_combinations', models.IntegerField(default=0)),
                ('completed_combinations', models.IntegerField(default=0)),
                ('best_params', models.JSONField(blank=True, null=True)),
                ('best_score', models.FloatField(blank=True, null=True)),
                ('all_results', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='optimizer_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
