# Generated by Django 5.0.6 on 2026-05-04 15:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TradingProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "max_daily_loss",
                    models.DecimalField(decimal_places=2, default=10000, max_digits=14),
                ),
                (
                    "profit_lock_amount",
                    models.DecimalField(decimal_places=2, default=5000, max_digits=14),
                ),
                ("max_daily_trades", models.IntegerField(default=50)),
                (
                    "max_position_size",
                    models.DecimalField(
                        decimal_places=2, default=100000, max_digits=14
                    ),
                ),
                ("max_positions", models.IntegerField(default=10)),
                (
                    "max_drawdown",
                    models.DecimalField(decimal_places=4, default=0.2, max_digits=5),
                ),
                (
                    "max_loss_per_trade",
                    models.DecimalField(decimal_places=2, default=2000, max_digits=14),
                ),
                (
                    "min_rr_ratio",
                    models.DecimalField(decimal_places=2, default=1.5, max_digits=5),
                ),
                ("require_stop_loss", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trading_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RiskEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_type", models.CharField(max_length=32)),
                ("severity", models.CharField(max_length=16)),
                ("reason", models.TextField()),
                ("metadata", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "event_type"],
                        name="risk_riskev_user_id_9cd12c_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="risk_riskev_created_256c90_idx"
                    ),
                ],
            },
        ),
    ]
