# Generated by Django 5.0.6 on 2026-06-05 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradingprofile',
            name='max_daily_loss_pct',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Max daily loss % of capital. e.g. 0.05 = 5%', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='tradingprofile',
            name='max_position_pct',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Max position size % of capital. e.g. 0.10 = 10%', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='tradingprofile',
            name='risk_per_trade_pct',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Per trade max loss % of capital. e.g. 0.02 = 2%', max_digits=5, null=True),
        ),
    ]
