# Generated by Django 5.0.6 on 2026-06-09 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0002_pct_risk_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradingprofile',
            name='exit_mode',
            field=models.CharField(choices=[('gtt_oco', 'GTT OCO — Fixed SL/Target'), ('smart_trail', 'Smart Trail — Trailing SL'), ('both', 'Both — Trail + GTT backup')], default='gtt_oco', help_text='Exit order type for live options trades', max_length=20),
        ),
    ]
